before:
  hooks:
    - go mod download
builds:
  - id: kpkg
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - openbsd
      - netbsd
      - dragonfly
      - solaris
    goarch:
      - amd64
      - arm
      - arm64
      - 386
      - ppc64
      - ppc64le
      - mips
      - mipsle
      - mips64
      - mips64le
      - s390x
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X "main.goversion=$(go version)"
  - id: kpkg-macos
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
    hooks:
      post: gon gon.hcl
archives:
  - format: binary
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
release:
  prerelease: auto
