before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - openbsd
      - netbsd
      - dragonfly
      - solaris
    goarch:
      - amd64
      - arm
      - arm64
      - 386
      - ppc64
      - ppc64le
      - mips
      - mipsle
      - mips64
      - mips64le
      - s390x
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X "main.goversion=$(go version)"
archives:
  - format: binary
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
