name: build binaries

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]-rc[0-9]+'

jobs:
  build:
    name: Build the binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15'

      - name: Build
        run: go build -o kpkg -s -w -X main.version=${{ github.ref }} -X main.commit=${{ github.sha }} -X "main.goversion=$(go version)"

      - run: chmod +x ./kpkg
      - run: ./kpkg version

      - name: upload binary artifacts
        uses: actions/upload-artifact@v2
        with:
          name: kpkg
          path: kpkg


