name: build binaries

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9](-rc[0-9]+)?'

jobs:
  build:
    name: Build the binaries
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ contains( ${{ github.ref }}, "rc" ) }}


